include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
obj-y   +=  nt35595_fhd_dsi_cmd_truly_nt50358.o
obj-y   +=  nt35590_hd720_dsi_cmd_auo.o
obj-y   +=  otm9608_qhd_dsi_cmd.o
obj-y   +=  otm9608_qhd_dsi_vdo.o
obj-y   +=  otm9608_fwvga_dsi_cmd.o
obj-y   +=  otm9608_wvga_dsi_cmd.o

